### ISSUE TITLE
Mismatch on expected env variable name between travis and tic for SSH key

### ISSUE THREAD

**Issue by gadenbuie** [ropensci/tic#214]
You are likely already aware of this, but I just discovered (the hard and painful way) that due to the [recent change in ropenscilabs/travis](https://github.com/ropenscilabs/travis/commit/0b3e6e6f10782babc9941eb3ea714df30fd84393) the private SSH key is now stored in the `TRAVIS_DEPLOY_KEY_<endpoint>` environment variable.

It seems that many of the steps in `tic` -- in particular `step_setup_ssh()` and `do_pkgdown()` -- assume that the name of the env var is `id_rsa`. IIUC, you can manually run `step_setup_ssh()` and specify the `name` outside `do_pkgdown()`.

```
get_stage("before_deploy") %>%
  add_step(step_setup_ssh("TRAVIS_DEPLOY_KEY_COM")
do_pkgdown()
```

But `do_pkgdown()` doesn't expose the `name` parameter, which could be one solution to this mismatch.

In the end, I (for the time being) created the key with

```r
travis::use_travis_deploy(key_name_private = "id_rsa")
```

The error messages in the logs when this fails are misleading. First, the `step_setup_ssh()` is skipped but it's hard to tell why.

```
> tic::before_deploy()
✔ Loading tic stage configuration from tic.R
Skipping before_deploy: step_setup_ssh()
function () 
{
    if (!private$install_ssh_keys$check()) {
        return(FALSE)
    }
    if (!private$add_to_known_hosts$check()) {
        return(FALSE)
    }
    if (!private$test_ssh$check()) {
        return(FALSE)
    }
    TRUE
}
<environment: 0x7fada91c5bc8>
```

Then, the push deploy step will fail due to the privatekey not being set.

```
Initializing Git repo at docs
Staging: .
Checking changed files
Committing to /Users/travis/build/<owner>/<repo>/docs/.git
No upstream branch found
Pushing to remote
git push --force tic-remote HEAD
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/<owner>/<repo>.git/'
```

**Comment by pat-s** [comment]
Sorry a lot for this. I am aware of the change since I did it in {travis} but forgot to apply it to {tic}. No excuse for this.

> 
> In the end, I (for the time being) created the key with
> 
> travis::use_travis_deploy(key_name_private = "id_rsa")

That is correct for a workaround.

I just pushed a fix (d6ffd8f56d436dd708b510eba04c74734a802f5a) that supports the new default name but also comes with support for the old "id_rsa". 

The initial idea was to resolve the hidden dep from {travis} to {tic} by making the naming of the keys flexible.
I will make these arguments available in `use_tic()` soon. For now, the quick fix should hopefully do it :)

**Comment by gadenbuie** [comment]
No worries! I just got unlucky and fell into a temporal dead zone. The hard part is that there are a lot of confounding factors so it took a while to narrow down to the issue. (Btw, the new `tic::use_tic()` wizard is 💯!)

The fix looks good, but one question. The env var created by `travis::use_travis_deploy()` is `TRAVIS_DEPLOY_KEY_COM`. Will this key still be found if you look for `TRAVIS_DEPLOY_KEY`? 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/5420529/72206100-dfd07080-3457-11ea-8b1e-ff41e558f65b.png">

**Comment by gadenbuie** [comment]
This is slightly off-topic, but one thing wasn't clear when I used the new `tic::use_tic()`. If you pick a matrix of old/current/dev releases and end up with, say, 6 builds on Travis, do you need to do any extra work to decide which one of the matrix builds will also build the pkgdown docs?

**Comment by pat-s** [comment]
> temporal dead zone

I like the word. Matches the status pretty precisely. 

> (Btw, the new tic::use_tic() wizard is 💯!)

Thanks. Joint work with @krlmlr 

> The env var created by travis::use_travis_deploy() is TRAVIS_DEPLOY_KEY_COM. Will this key still be found if you look for TRAVIS_DEPLOY_KEY?

Indeed, this will probably not work. There is no partial matching. This happens if you do a "quickfix" on the go ;) 

I decided to remove the endpoint suffix in {travis} as this simplifies things when checking for it. This means no `TRAVIS_DEPLOY_KEY_ORG` but only `TRAVIS_DEPLOY_KEY`. As the private keys only get added to the respective Travis CI endpoint repo, this should be fine. Its more important to have the endpoint in the name of the public key stored within the GH repo.

You need to run `travis::use_travis_deploy()` again and eventually clean up the already created keys.

> If you pick a matrix of old/current/dev releases and end up with, say, 6 builds on Travis, do you need to do any extra work to decide which one of the matrix builds will also build the pkgdown docs?

Thanks. Good question!
So what we do is to condition on an env var `BUILD_PKGDOWN` in `tic.R`. However, this one is currently not set in the travis-matrix builds so it actually won't work. So you caught another bug here 🎉 

I just pushed a fix and also added a section about this to `?tic::use_travis_yml()`. I hope this makes it more clear.

```r
if (ci_has_env("BUILD_PKGDOWN")) {
  do_pkgdown()
}
```

**Comment by gadenbuie** [comment]
So if I'm reading the source correctly, it seems like more work is needed to install the ssh key when the env name is `TRAVIS_DEPLOY_KEY`.

In the lines below it seems that the ssh key will be written to `~/.ssh/TRAVIS_DEPLOY_KEY` but I don't think ssh is told to use this key for github.

https://github.com/ropenscilabs/tic/blob/25b318e89c75676af0d3eb83d719761d0899ecaf/R/steps-ssh.R#L69-L76

Here are the logs from a recent build where you can see that `~/.ssh/TRAVIS_DEPLOY_KEY` is created but ssh looks for `id_*` public keys.

<details><summary>Build log</summary>

```
Running before_deploy: step_setup_ssh()
Writing deploy key to ~/.ssh/TRAVIS_DEPLOY_KEY
Running ssh-keyscan for github.com
# github.com:22 SSH-2.0-babeld-378a3119
# github.com:22 SSH-2.0-babeld-378a3119
# github.com:22 SSH-2.0-babeld-378a3119
|1|<...ssh-rsa key...>
Adding to ~/.ssh/known_hosts
Trying to ssh into git@github.com
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /home/travis/.ssh/config
debug1: /home/travis/.ssh/config line 1: Applying options for *
debug1: /home/travis/.ssh/config line 2: Deprecated option "useroaming"
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to github.com [192.30.255.113] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/travis/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: Remote protocol version 2.0, remote software version babeld-378a3119
debug1: no match: babeld-378a3119
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /home/travis/.ssh/known_hosts:2
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/travis/.ssh/id_rsa
debug1: Trying private key: /home/travis/.ssh/id_dsa
debug1: Trying private key: /home/travis/.ssh/id_ecdsa
debug1: Trying private key: /home/travis/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).
```
</details>

**Comment by pat-s** [comment]
I might need to have to revert back to `id_rsa` for the private key name. The reason is that `git2r::fun` also do not work if the private key is named differently and I would need to pass the custom name through many functions.

I don't think this is worth the effort even though I would have liked to have a more descriptive env var name than "id_rsa" for the user.

**Comment by gadenbuie** [comment]
How often are multiple ssh keys installed in the deploy step? It seems reasonable to me that the deploy key always be written to `~/.ssh/id_rsa` regardless of the name of the env var that it's stored in.

In other words, I think you could probably hard code the `deploy_key_path` as `~/.ssh/id_rsa`. If you really need to cover edge cases where multiple ssh keys are used in a job, you could allow overwriting existing keys so users could install the second key before using it; or you could expose the name of the key as an argument defaulting to the env var name. But setting up custom ssh keys for a spcific hostname seems out of scope to me (or at least if that's something I needed to do I probably wouldn't use tic to orchestrate it).

**Comment by pat-s** [comment]
You only need one valid key pair in a build which has permission to deploy to your repo.
This is a bit fiddly on Travis including the naming and manual creation of the key pair. Things are much easier on Circlei CI when it comes to deployment.

The whole renaming was built on the idea to make {tic} not dependent on a default set in {travis} by making the key pair names dynamic.
So I guess to finish this up there is no other way to go down the route of passing this flexibility through all instances. 

> It seems reasonable to me that the deploy key always be written to ~/.ssh/id_rsa regardless of the name of the env var that it's stored in.

Yeah this could maybe make things easier. Just before calling `ssh` we simply rename it to `id_rsa` internally so that all the other tools are happy.

I hope to finish this in a robust way today so that the interruption is as small as possible.

**Comment by pat-s** [comment]
I've now ensured (and checked) that deployment works if

- and env var `id_rsa` exists with its respective public key counterpart (old default) without user changes needed
- and env var `TRAVIS_DEPLOY_KEY` exists with its respective public key counterpart (new default) without user changes needed
- `travis::use_travis_deploy()` was called with a custom private key name and that private key is supplied via the `travis_private_key_name` arg in macros `do_pkgdown()` and `do_bookdown()` 

Let me know if you come across more deployment issues! I also want to be more verbose if the deployment setup failed within the build. See #216

**Comment by pat-s** [comment]
Assumed to be solved :)
