### ISSUE TITLE
Building pkgdown website twice ? 

### ISSUE THREAD

**Issue by lrnv** [ropensci/tic#238]
Hi, 

I'm working on github.com/lrnv/cort, results on travis can be see there : https://travis-ci.org/github/lrnv/cort

I seems like the `devel` build is trying to build pkgdown and fails while trying to push it on github, since the `release` build is a little faster and did it first. 

Why are the 2 build trying to push ? I thought the default configuration will be that only one of them will push ? 

All i did was using the `tic` defaut setup via tic::use_tic().

**Comment by pat-s** [comment]
You`re right in your observation.

In practice we do not know upfront how the build matrix will look like due to the amount of possible options (at least how we handle things on Travis).

Therefore we cannot set the runner which will do the pkgdown deployment by default because we wont't know if that runner will really exist in the end.
In practice, we recommend to condition the pkgdown deployment on an env var like:

tic.R

```r
if (ci_on_travis() && ci_has_env("PKGDOWN") {
  # creates pkgdown site and pushes to gh-pages branch
  do_pkgdown()
}
```

`.travis.yml`

```yml
matrix:
  include:
    - os: osx
      r: release
    - os: linux
      r: release
      env:
      - BUILD_PKGDOWN=true
```

I'll add a note for this to the vignettes.

**Comment by lrnv** [comment]
Thanks for the quick fix !!
