### ISSUE TITLE
Temporary {Rcpp} problem - need for dev version

### ISSUE THREAD

**Issue by lrnv** [ropensci/tic#239]
Hey, 

Looking at the failling build logs on appveyor [there](https://ci.appveyor.com/project/lrnv/cort/builds/31711797/job/b89l4xpv2537vfvb), it seems that : 

- Since i have no `src/` folder, the `Rtools` is not installed.
- The `tic` package is downloaded from github
- `tic` depends on a commit from Rcpp that is not yet pushed on CRAN, so `Rcpp` is downloaded from github
- `Rccp` need `Rtools` to be compiled.

I'm Okay with my buid failing, i just wanted you guys to now about it ;)

**Comment by pat-s** [comment]
Thanks. We already know about this and indeed the issue is caused by a faulty Rcpp CRAN release (v1.0.4) (even though Dirk might argue differently here). As a workaround we temporarily depend on Rcpp dev in DESCRIPTION.

This fixes R-devel issues on Travis and GitHub Actions.
Unfortunately we do not support installations from source on Appveyor (for various reasons) and hence builds will continue to fail until there is a patched CRAN release for Rcpp.

Some details: Rcpp is not a dep of tic. The build fails because the installation of {fs} fails which is a dep of {usethis} and the latter is a dep of {tic}.

I wanted to open an informative issue about this anyway but got distracted. Let's leave this open until the issue is resolved.

**Comment by lrnv** [comment]
Yes i had the same problem with `fs` on R-devel a few days back, which is indeed solved now. `pkgdown` also depends on `fs`. The fix in Rcpp should be upstream in cran as soon as 1.0.5 if i understood correctly.
