### ISSUE TITLE
main.yml -> tic.yml for GHA?

### ISSUE THREAD

**Issue by krlmlr** [ropensci/tic#253]
Can we rename efficiently and propagate to existing repositories?

**Comment by pat-s** [comment]
Changing the default file that is written is not an issue.

Accounting for multiple locations in `update_yml()` is a bit more troublesome.

Now could be a good time since not so many people have implemented the update mechanism yet.

**Comment by krlmlr** [comment]
I rather like the badge, not the color though:

[![R build status](https://github.com/krlmlr/dm/workflows/tic/badge.svg)](https://github.com/krlmlr/dm/actions)

**Comment by pat-s** [comment]
It's short but a little bit non-descriptive? That's why I included "R CMD Check" in the current version.

The current default focuses on R CMD Check only however, which might be wrong if one uses it for other project types like blogdown/bookdown.

Not really happy with any option currently but maybe your suggestion is the best compromise for now 👍 (new issue needed)
