### ISSUE TITLE
use_tic can't load `travis` even though travis not used?

### ISSUE THREAD

**Issue by andrewcstewart** [ropensci/tic#280]
After running `tic:use_tic()` I get the following error at the end of the wizard:

```
Selection: 1
If setup fails, rerun with:
`tic::use_tic(wizard = FALSE, linux = "ghactions", mac = "ghactions", windows = "none", deploy = "ghactions", matrix = "none")`

── Setting up the CI providers ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Next we are getting the selected CI providers ready for deployment. This requires some interaction with their API and you may need to create an API
token.

Error in loadNamespace(name) : there is no package called ‘travis’
```

This doesn't make much sense to me considering I haven't selected travis for anything.

**Comment by pat-s** [comment]
This is because `use_ghactions_deploy()` is calling some helper funs from {travis}. {travis} itself is not installed when installing {tic} as it is only in suggests. 

I am thinking of outsourcing all the CI-agnostic helpers into a separate package which is then imported during installation of {tic}.
